name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-user:
    runs-on: ubuntu-latest
    steps:
      - name: Sarasa
        run: echo Sarasa
  create-vanilla:
    runs-on: ubuntu-latest
    needs: create-user
    steps:
      - uses: actions/checkout@v2

      - name: Show file
        run: cat text.txt
      
      - name: Show file2
        run: cat text2.txt
  create-base:
    runs-on: ubuntu-latest
    needs: create-vanilla
    steps:
      - name: Sarasa
        run: echo Sarasa