name: 04 NDK Images

on:
  workflow_dispatch:

jobs:
  build_ndk_r19_image:
    runs-on: ubuntu-latest 
    env:
      ndk_version: "r19"
      image_output: ""
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: base_image.yaml
      
      - name: 'Run packer + ansible'
        run: |
          cat base-image-version/artifact.txt
          echo ${{env.ndk_version}}
          echo this should call build_ndk.sh
          echo "win10-packer-ndk-$(date +'%Y%m%d%H%M%S')" > artifact.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ndk-${{env.ndk_version}}-image-version
          path: artifact.txt

  build_ndk_r21d_image:
    runs-on: ubuntu-latest 
    env:
      ndk_version: "r21d"
      image_output: ""
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: base_image.yaml
      
      - name: 'Run packer + ansible'
        run: |
          cat base-image-version/artifact.txt
          echo ${{env.ndk_version}}
          echo this should call build_ndk.sh
          echo "win10-packer-ndk-$(date +'%Y%m%d%H%M%S')" > artifact.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ndk-${{env.ndk_version}}-image-version
          path: artifact.txt
    
  build_ndk_r23b_image:
    runs-on: ubuntu-latest 
    env:
      ndk_version: "r23b"
      image_output: ""
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: base_image.yaml
      
      - name: 'Run packer + ansible'
        run: |
          cat base-image-version/artifact.txt
          echo ${{env.ndk_version}}
          echo this should call build_ndk.sh
          echo "win10-packer-ndk-$(date +'%Y%m%d%H%M%S')" > artifact.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ndk-${{env.ndk_version}}-image-version
          path: artifact.txt
