name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-step:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-${{ github.sha }}
  create-unity-1:
    runs-on: ubuntu-latest
    steps:
      - name: Sarasa
        run: echo Sarasa
  create-unity-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show file
        run: cat text.txt
  create-unity-3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Sarasa
        run: echo Sarasa