name: Vanilla-Image

# Controls when the action will run. 
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-vanilla:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: 72213076
          workflow_conclusion: success
          branch: master